---
title: "git_01"
author: "Math_115"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

Never tell me that not one star of all  
That slip from heaven at night and softly fall  
Has been picked up with stones to build a wall.  

Some laborer found one faded and stone-cold,  
And saving that its weight suggested gold  
And tugged it from his first too certain hold,  

He noticed nothing in it to remark.  
He was not used to handling stars thrown dark  
And lifeless from an interrupted arc.  

He did not recognize in that smooth coal  
The one thing palpable besides the soul  
To penetrate the air in which we roll.  

He did not see how like a flying thing  
It brooded ant eggs, and bad one large wing,  
One not so large for flying in a ring,  

And a long Bird of Paradise's tail  
(Though these when not in use to fly and trail  
It drew back in its body like a snail):  

Nor know that be might move it from the spot -  
The harm was done: from having been star-shot  
The very nature of the soil was hot  
